version: '2'
services:

    pomodoro:
        build: .
        image: asnelzin/pomodoro:latest
        container_name: pomodoro
        hostname: pomodoro
        restart: always

        ports:
          - "5080:8080"

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
