version: '2'
services:

    pomodoro:
        build: .
        image: asnelzin/pomodoro:latest
        container_name: pomodoro
        hostname: pomodoro
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        env_file:
          - secrets.env

    nginx:
        build: nginx
        image: asnelzin/pomodoro:nginx
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        depends_on:
            - pomodoro

        volumes:
            - ./etc/ssl:/etc/nginx/ssl

        volumes_from:
            - pomodoro

        ports:
            - "80:80"
            - "443:443"

        environment:
            - LETSENCRYPT=true
            - LE_EMAIL=asnelzin@gmail.com
            - LE_FQDN=dev.nelzin.ru

            - SSL_CERT=pomodoro-crt.pem
            - SSL_KEY=pomodoro-key.pem
